# 合并 deployment/docker/.env + 生产覆盖 + worker 关键变量 → cloud .env
param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path,
  [string]$OutFile = ""
)

$ErrorActionPreference = "Stop"
if (-not $OutFile) {
  $OutFile = Join-Path $RepoRoot "deployment/cloud/tencent-lighthouse/.env"
}

function Read-EnvFile([string]$Path) {
  $map = @{}
  if (-not (Test-Path $Path)) { return $map }
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq "" -or $line.StartsWith("#")) { return }
    $idx = $line.IndexOf("=")
    if ($idx -lt 1) { return }
    $k = $line.Substring(0, $idx).Trim()
    $v = $line.Substring($idx + 1)
    $map[$k] = $v
  }
  return $map
}

$merged = @{}
(Read-EnvFile (Join-Path $RepoRoot "deployment/docker/.env")).GetEnumerator() | ForEach-Object { $merged[$_.Key] = $_.Value }
(Read-EnvFile (Join-Path $RepoRoot "apps/worker/.env")).GetEnumerator() | ForEach-Object { $merged[$_.Key] = $_.Value }
(Read-EnvFile (Join-Path $RepoRoot "deployment/cloud/tencent-lighthouse/env.production.example")).GetEnumerator() | ForEach-Object { $merged[$_.Key] = $_.Value }

$merged["NODE_ENV"] = "production"
$merged["DB_HOST"] = "postgres"
$merged["DB_SYNCHRONIZE"] = "false"
$merged["TEST_AUTH_ENABLED"] = "false"
$merged["SWAGGER_ENABLED"] = "false"
$merged["VITE_PUBLIC_ORIGIN"] = "https://axislab.top"
$merged["CORS_ORIGIN"] = "https://axislab.top"
$merged["GRAFANA_ROOT_URL"] = "https://axislab.top/ops/grafana/"
$merged["WECHAT_REDIRECT_URI"] = "https://axislab.top/api/auth/wechat/callback"
$merged["COLLAB_REDIS_URL"] = "redis://redis:6379/0"
$merged["REDIS_HOST"] = "redis"
$merged["API_SERVICE_URL"] = "http://api-service:3000"
$merged["FOUNDRY_IMAGE_PREFIX"] = "foundry"
$merged["FOUNDRY_IMAGE_TAG"] = "latest"
$merged["LOG_LEVEL"] = "warn"
$merged["DB_LOGGING"] = "false"

$lines = @("# generated by prepare-env.ps1 at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$merged.GetEnumerator() | Sort-Object Name | ForEach-Object {
  $lines += "$($_.Key)=$($_.Value)"
}
$lines | Set-Content -Path $OutFile -Encoding UTF8

# docker compose 读取 deployment/docker/.env
Copy-Item -Force $OutFile (Join-Path $RepoRoot "deployment/docker/.env")
Write-Host "Wrote $OutFile"
