import { Route } from '../interfaces/route.interface.js';

/**
 * 路由配置
 */
export const ROUTES: Route[] = [
  // API 服务路由
  // 注意：Gateway 的全局前缀是 'api'，所以路径配置中不需要包含 '/api' 前缀
  // 请求 /api/v1/users 会被 NestJS 处理为 /v1/users（去掉全局前缀）
  // 关键链路：users.list / users.get 走 RPC（可灰度/可回滚）
  {
    path: '/v1/users',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.findAll',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/users/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.findOne',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/users/:id/memberships',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.memberships.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/users/:id/context',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.adminContext.get',
    rpcTimeoutMs: 30000,
    methods: ['GET'],
  },
  // users 写接口：走 RPC（按 method 精确匹配）
  {
    path: '/v1/users',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.create',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/users/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/users/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'users.remove',
    rpcTimeoutMs: 8000,
    methods: ['DELETE'],
  },
  // companies 入口/管理：走 RMQ RPC（与 API CompaniesRpcController 消息模式一致）
  {
    path: '/v1/companies',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.findAll',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/creation-quota',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.creationQuota',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.findOne',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/memberships/me',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.membership.findActive',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.create',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/quick-create',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.quickCreate',
    rpcTimeoutMs: 20000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/draft',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.createDraft',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/setup-recommendation',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.setupRecommendation',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/wizard/template-recommendations',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.recommendTemplates',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/wizard/patch-organization-draft',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.patchOrganizationDraft',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/complete',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.completeWizard',
    rpcTimeoutMs: 20000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/status',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.changeStatus',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/companies/:id/company-profile/sync',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/companies/:id/company-profile/sync',
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/ceo-decision-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoDecision.getConfig',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/ceo-decision-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoDecision.updateConfig',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/companies/:id/heartbeat-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.heartbeat.getConfig',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/heartbeat-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.heartbeat.updateConfig',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/companies/:id/scheduled-playbooks',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'scheduledPlaybooks.list',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/scheduled-playbooks',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'scheduledPlaybooks.create',
    rpcTimeoutMs: 12000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/scheduled-playbooks/:scheduleId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'scheduledPlaybooks.get',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/scheduled-playbooks/:scheduleId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'scheduledPlaybooks.update',
    rpcTimeoutMs: 12000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/companies/:id/scheduled-playbooks/:scheduleId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'scheduledPlaybooks.remove',
    rpcTimeoutMs: 12000,
    methods: ['DELETE'],
  },
  {
    path: '/v1/companies/:id/scheduled-playbooks/:scheduleId/run-now',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'scheduledPlaybooks.triggerNow',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/ceo-layer-config/sync-from-template',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoLayerConfig.syncFromTemplate',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/ceo-layer-config/atomic-sync',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoLayerConfig.atomicSync',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/ceo-layer-config/sync-agent-skills',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoLayerConfig.syncSkillsToAgent',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/ceo-layer-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoLayerConfig.getConfig',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/ceo-layer-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.ceoLayerConfig.updateConfig',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/companies/:id/marketplace-skills/available-versions',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.skills.listAvailableVersions',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/marketplace-skills/upgrade-version',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.skills.upgradeVersion',
    rpcTimeoutMs: 12000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/marketplace/hire-requests',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.hireRequests.create',
    rpcTimeoutMs: 20000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/marketplace/hire-requests',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.hireRequests.list',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/marketplace/hire-requests/:hireId/approve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.hireRequests.approve',
    rpcTimeoutMs: 120000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/marketplace/hire-requests/:hireId/reject',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.hireRequests.reject',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/marketplace/hire-requests/:hireId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.hireRequests.findOne',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/companies/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'companies.remove',
    rpcTimeoutMs: 15000,
    methods: ['DELETE'],
  },
  // organization：组织结构管理走 RPC
  {
    path: '/v1/organizations/tree',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.tree',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/platform/departments',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'platform.departments.publicList',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/organizations/nodes',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.create',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/organizations/departments/from-platform',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.department.addFromPlatform',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/organizations/nodes/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/organizations/nodes/:id/move',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.move',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/organizations/nodes/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.remove',
    rpcTimeoutMs: 8000,
    methods: ['DELETE'],
  },
  {
    path: '/v1/organizations/nodes/:id/agents',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.agents',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/organizations/nodes/:id/reporting-chain',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.reportingChain',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/organizations/nodes/:id/skills',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.skills.list',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/organizations/nodes/:id/skills/bind',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.skills.bind',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/organizations/nodes/:id/skills/unbind',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.skills.unbind',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/organizations/audit-logs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.audit.logs',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/organizations/nodes/:id/knowledge-summary',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'organization.node.knowledgeSummary',
    rpcTimeoutMs: 30000,
    methods: ['GET'],
  },
  // agents
  {
    path: '/v1/agents',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.findAll',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/audit-logs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.auditLogs',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/ui-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.uiConfig',
    rpcTimeoutMs: 3000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/system-approval',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.systemApproval',
    rpcTimeoutMs: 3000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/batch-recruit',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.batchRecruit',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/agents/:id/workspace',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.workspace.get',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/:id/effective-skills',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.effectiveSkills',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/:id/memory-stats',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.memoryStats',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/:id/marketplace-llm-sync',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.refreshMarketplaceLlmSnapshot',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/agents/:id/subordinates',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.management.subordinates',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/:id/supervisor-chain',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.management.supervisorChain',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents/:id/supervisor',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.hierarchy.setSupervisor',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/agents/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.findOne',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/agents',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.create',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/agents/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/agents/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.remove',
    rpcTimeoutMs: 8000,
    methods: ['DELETE'],
  },
  {
    path: '/v1/agents/:id/approve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.approve',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/agents/:id/status',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.updateStatus',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/agents/:id/assign-node',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.assignToNode',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/agents/:id/skills',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.bindSkills',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/agents/:id/skills/unbind',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'agents.unbindSkills',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  // Legacy MCP Tools (independent resource) routes are intentionally removed in Phase F2.
  // - Admin UI is unified to Skills.
  // - Runtime MCP tool resolution is Skill-snapshot based.
  // - Keeping passthrough routes here would only preserve dead endpoints and slow down migration.
  // platform-settings（直连 API Nest Controller：api/admin/platform-settings）
  {
    path: '/v1/admin/platform-settings/fallback-model',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/fallback-model',
    methods: ['GET', 'PATCH'],
  },
  {
    path: '/v1/admin/platform-settings/memory-default-embedding-model',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/memory-default-embedding-model',
    methods: ['GET', 'PATCH'],
  },
  {
    path: '/v1/admin/platform-settings/role-default-global-skills',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/role-default-global-skills',
    methods: ['GET', 'PATCH'],
  },
  {
    path: '/v1/admin/platform-settings/intent-layer-global-settings',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/intent-layer-global-settings',
    methods: ['GET', 'PATCH'],
  },
  {
    path: '/v1/admin/platform-settings/intent-layer-rules',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/intent-layer-rules',
    methods: ['GET', 'PATCH'],
  },
  {
    path: '/v1/admin/platform-settings/intent-layer-preview',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/intent-layer-preview',
    methods: ['PATCH'],
  },
  {
    path: '/v1/admin/platform-settings/intent-layer-output-schema',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/intent-layer-output-schema',
    methods: ['GET'],
  },
  {
    path: '/v1/admin/platform-settings/ceo-pipeline-output-schema',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/ceo-pipeline-output-schema',
    methods: ['GET'],
  },
  {
    path: '/v1/admin/platform-settings/collaboration-main-chain',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/admin/platform-settings/collaboration-main-chain',
    methods: ['GET', 'PATCH'],
  },
  // skills
  // skills management (HTTP passthrough to API v1 controller)
  {
    path: '/v1/skills/:id/bind-mcp-tools',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/v1/skills/:id/bind-mcp-tools',
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/bind-tools',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/v1/skills/:id/bind-tools',
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/test-mcp-connection',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/v1/skills/:id/test-mcp-connection',
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/versions',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/v1/skills/:id/versions',
    methods: ['GET'],
  },
  {
    path: '/v1/skills/:id',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/v1/skills/:id',
    methods: ['PUT', 'DELETE'],
  },
  {
    path: '/v1/skills',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/v1/skills',
    methods: ['GET', 'POST'],
  },
  // legacy skills rpc routes
  {
    path: '/v1/skills',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.findAll',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/skills/validate-company-bindings',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.validateCompanyBindings',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.findOne',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/skills',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.create',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/skills/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.remove',
    rpcTimeoutMs: 8000,
    methods: ['DELETE'],
  },
  {
    path: '/v1/skills/:id/revisions',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.revisions.list',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/skills/:id/revisions/import-from-artifact',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.revisions.importFromArtifact',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/revisions/:revisionId/publish',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.revisions.publish',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/revisions/:revisionId/review',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.revisions.review',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/revisions/:revisionId/revoke',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.revisions.revoke',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/skills/:id/revisions/:revisionId/rollback',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'skills.revisions.rollback',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  // memory（RAG / 公司知识）
  {
    path: '/v1/memory/entries',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.entries.list',
    rpcTimeoutMs: 10000,
    methods: ['GET'],
  },
  {
    path: '/v1/memory/entries',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.entries.store',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/entries/:entryId/archive',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.entries.archive',
    rpcTimeoutMs: 30000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/memory/entries/:entryId/unarchive',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.entries.unarchive',
    rpcTimeoutMs: 30000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/memory/search',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.search',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/search/hierarchy',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.search.hierarchy',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/search/routed',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.search.routed',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/consolidation/request',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.consolidation.request',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/session/backfill',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.session.backfill.request',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/summarize',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.summarize',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/documents/ingest',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.document.ingest',
    rpcTimeoutMs: 120000,
    methods: ['POST'],
  },
  {
    path: '/v1/memory/documents/ingest-async',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.document.ingestAsync',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/memory',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.search.routed',
    rpcTimeoutMs: 30000,
    methods: ['GET', 'POST'],
  },
  {
    path: '/memory/ingest',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.entries.store',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/memory/consolidate',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'memory.consolidation.request',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  // collaboration（群聊 / 协作控制面；RPC 与 RMQ/DB 冷启动对齐 dashboard/companies）
  {
    path: '/v1/collaboration/rooms',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/main',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.findMain',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/department-by-slug',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.findDepartmentBySlug',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.findOne',
    /** api-rpc-queue 积压时易排队超时，略高于原 15s+dev min 20s 的合成上限 */
    rpcTimeoutMs: 60000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/read',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.markRead',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/collaboration-mode',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.updateCollaborationMode',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/orchestration-runs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.orchestrationRuns.listByRoom',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/programs/active',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.programs.getActive',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/programs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.programs.listByRoom',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/programs/:programId/confirm',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.programs.confirm',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/threads',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.threads.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/threads',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.threads.create',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/threads/:threadId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.threads.update',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/messages',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.messages.send',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/messages/search',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.messages.search',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/messages',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.messages.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/members',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.members.list',
    rpcTimeoutMs: 60000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/main-room-draft',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.mainRoomDraft.state.get',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/main-room-draft/strategy-goal',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.mainRoomDraft.strategyGoal.patch',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/main-room-draft/distribution',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.mainRoomDraft.distribution.patch',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/dispatch-plan/draft',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.dispatchPlanDraft.state.get',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/rooms/:roomId/dispatch-plan/draft',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.dispatchPlanDraft.patch',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/collaboration/members',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.members.add',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/members/remove',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.members.remove',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/rooms/summary',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.room.summary.request',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/members/add-from-organization-node',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.members.addFromOrganizationNode',
    rpcTimeoutMs: 20000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/rooms/department',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.createDepartment',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/rooms/direct',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.rooms.findOrCreateDirect',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/organization-nodes/search',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.organizationNodes.search',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/collaboration/ceo-approvals/:approvalId/resolve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.ceoApprovals.resolve',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/collaboration/director-reports',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'collaboration.director.reportProgress',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  // tasks（任务操作系统 / 仪表盘）
  {
    path: '/v1/dashboard',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'dashboard.companySummary',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/daily-brief',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'dailyBrief.getForUser',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/dashboard/billing',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'dashboard.billingSummary',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/billing/agent-usage/by-day',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.agentUsage.listCompanyDaily',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/billing/agent-daily',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.agentUsage.listRange',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/billing/daily-trend',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.costTrend.get',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/dashboard/board-runs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'dashboard.boardRunSummary',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/task-runs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.runs.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/task-runs/:runId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.runs.get',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/task-runs/:runId/interventions',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.runs.intervene',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/task-runs/:runId/execution-logs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.executionLogs.listByRunId',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/task-runs/:runId/trace-events',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'observability.trace.listByRunId',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  // billing（费用透明 / 预算 / 模型路由）
  {
    path: '/v1/billing/records',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.records.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/billing/records',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.record.append',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/billing/budgets',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.budgets.list',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/billing/budgets',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.budget.upsert',
    rpcTimeoutMs: 8000,
    methods: ['PUT'],
  },
  {
    path: '/v1/billing/settings',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.settings.get',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/billing/settings',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.settings.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/billing/model-router/resolve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.modelRouter.resolve',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/billing/check-allowance',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.checkAllowance',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/billing/recharge-orders',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.rechargeOrders.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/companies/:id/billing/recharge-orders',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.rechargeOrders.create',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/billing/recharge-orders/:orderId/approve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.rechargeOrders.approve',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/companies/:id/billing/recharge-orders/:orderId/reject',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'billing.rechargeOrders.reject',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/approvals',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/approvals/stats',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.stats',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/approvals',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.create',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/approvals/pending',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.listPending',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/approvals/:approvalId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.findOne',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/approvals/:approvalId/approve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.approve',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/approvals/:approvalId/reject',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.reject',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/approvals/consume-token',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.consumeExecutionToken',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/approvals/apply-gated-config',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'approval.applyGatedConfig',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/alerts',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'alerts.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/alerts/:id/resolve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'alerts.resolve',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/projects',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.findAll',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/projects',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.create',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/projects/:id/tasks',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.tasks.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/projects/:id/agents',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.agents.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/projects/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.findOne',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/projects/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.update',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/projects/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'projects.remove',
    rpcTimeoutMs: 15000,
    methods: ['DELETE'],
  },
  // file-assets：公司文件库 Registry
  {
    path: '/v1/file-assets/upload',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/file-assets/upload',
    methods: ['POST'],
  },
  {
    path: '/v1/file-assets/stats',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.getStats',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/file-assets',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.findAll',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/file-assets/:id/download-url',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.getDownloadUrl',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/file-assets/:id/download',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/file-assets/:id/download',
    methods: ['GET'],
    timeout: 120000,
    proxyResponseType: 'arraybuffer',
  },
  {
    path: '/v1/file-assets/:id/ingest',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.ingest',
    rpcTimeoutMs: 120000,
    methods: ['POST'],
  },
  {
    path: '/v1/file-assets/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.findOne',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/file-assets/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/file-assets/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'fileAssets.remove',
    rpcTimeoutMs: 15000,
    methods: ['DELETE'],
  },
  {
    path: '/v1/tasks',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.findAll',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.create',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/breakdown',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.requestBreakdown',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/dependencies',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.dependencies.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/:id/tree',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.tree',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/:id/execution-logs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.executionLogs.list',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/:id/execution-logs/grouped',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.executionLogs.groupedByRun',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/:id/execution-logs',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.executionLog.append',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/assign',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.assign',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/delegate',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.delegateByDirector',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/review',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.reviewByDirector',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/director/reviews/batch',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.reviewBatchByDirector',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/director/progress-report',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.director.generateProgressReport',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/progress',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.updateProgress',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/tasks/:id/department-pipeline/sequential',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.departmentPipeline.createSequential',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/department-pipeline/handoff',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.departmentPipeline.crossDepartmentHandoff',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/supervision/resolve',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.supervision.resolve',
    rpcTimeoutMs: 30000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/chat/dispatch',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.chat.dispatchToDepartment',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/chat/report',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.chat.reportToMain',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/chat/coordination-request',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.chat.requestCoordination',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/delegation-candidates',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.delegation.candidates',
    rpcTimeoutMs: 12000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/goals/by-room/:roomId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.goals.listByRoom',
    rpcTimeoutMs: 15000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/goals/ensure-main',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.goals.ensureMain',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/goals/assign',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.goals.assignToDepartmentDirector',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/goals/close-round',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.goals.closeRound',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id/goals/complete-main-room-distribution',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.goals.completeMainRoomDistributionChild',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/tasks/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.findOne',
    rpcTimeoutMs: 10000,
    methods: ['GET'],
  },
  {
    path: '/v1/tasks/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.update',
    rpcTimeoutMs: 15000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/tasks/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'tasks.remove',
    rpcTimeoutMs: 15000,
    methods: ['DELETE'],
  },
  // oauth 控制面：走 RPC
  {
    path: '/v1/oauth/bind/:userId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'oauth.bind',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/oauth/accounts/:userId',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'oauth.accounts',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/oauth/find-or-create',
    service: 'api',
    authRequired: false,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'oauth.findOrCreate',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  // webhooks 管理面：走 RPC；接收端 /webhooks/* 保持 HTTP
  {
    path: '/v1/webhooks',
    service: 'webhooks',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'webhooks',
    rpcPattern: 'webhooks.findAll',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/webhooks',
    service: 'webhooks',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'webhooks',
    rpcPattern: 'webhooks.create',
    rpcTimeoutMs: 8000,
    methods: ['POST'],
  },
  {
    path: '/v1/webhooks/:id',
    service: 'webhooks',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'webhooks',
    rpcPattern: 'webhooks.findOne',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/webhooks/:id',
    service: 'webhooks',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'webhooks',
    rpcPattern: 'webhooks.update',
    rpcTimeoutMs: 8000,
    methods: ['PATCH'],
  },
  {
    path: '/v1/webhooks/:id',
    service: 'webhooks',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'webhooks',
    rpcPattern: 'webhooks.remove',
    rpcTimeoutMs: 8000,
    methods: ['DELETE'],
  },
  {
    path: '/v1/webhooks/:id/history',
    service: 'webhooks',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'webhooks',
    rpcPattern: 'webhooks.history',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  // files：优先把非流式/控制面接口 RPC 化；上传/下载保持 HTTP（multipart/二进制更适合直连）
  {
    path: '/v1/files',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/files',
    methods: ['POST'],
  },
  {
    path: '/v1/files',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'files.list',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/files/:path(*)/url',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'files.getUrl',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/files/:path(*)/info',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'files.getInfo',
    rpcTimeoutMs: 5000,
    methods: ['GET'],
  },
  {
    path: '/v1/files/:path(*)',
    service: 'api',
    authRequired: true,
    transport: 'http',
    rewritePath: '/api/files/:path(*)',
    methods: ['GET'],
  },
  {
    path: '/v1/files/:path(*)',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'files.delete',
    rpcTimeoutMs: 8000,
    methods: ['DELETE'],
  },
  // 模板市场 / Agent 商城（浏览为平台级；导入创建公司、安装 Agent 需登录）
  {
    path: '/v1/templates',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'templates.findAll',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/templates/:id/preview',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'templates.preview',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/templates/:id/import',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'templates.import',
    rpcTimeoutMs: 60000,
    methods: ['POST'],
  },
  {
    path: '/v1/templates/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'templates.findOne',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/marketplace/agents',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.agents.findAll',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/marketplace/agents/:id/purchase',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.agents.purchase',
    rpcTimeoutMs: 15000,
    methods: ['POST'],
  },
  {
    path: '/v1/marketplace/agents/:id',
    service: 'api',
    authRequired: true,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'marketplace.agents.findOne',
    rpcTimeoutMs: 8000,
    methods: ['GET'],
  },
  {
    path: '/v1/*',
    service: 'api',
    target: '/api', // API Service 的全局前缀是 'api'，所以需要将 /v1/* 重写为 /api/*
    authRequired: true,
  },
  // auth HTTP 由 Gateway AuthController 独占；凭证校验走下方 RPC，不代理 /auth/* 到 API
  {
    path: '/auth/validate',
    service: 'api',
    authRequired: false,
    transport: 'rpc',
    rpcClientName: 'api',
    rpcPattern: 'auth.validate',
    rpcTimeoutMs: 5000,
  },
  // Webhooks 服务路由
  {
    path: '/webhooks/*',
    service: 'webhooks',
    target: '/webhooks',
    authRequired: false, // Webhooks 接收端点，不需要认证
  },
  // Webhooks 管理API路由（通过Gateway转发）
  {
    path: '/v1/webhooks/*',
    service: 'webhooks',
    target: '/api/webhooks', // Webhooks Service的实际路径（全局前缀api + 控制器路径webhooks）
    authRequired: true, // Webhook管理API需要认证
  },
  // Worker 服务路由
  {
    path: '/worker/*',
    service: 'worker',
    target: '/worker',
    authRequired: true,
  },
];

/**
 * 根据路径查找路由
 */
function matchPattern(pattern: string, path: string): Record<string, string> | null {
  if (pattern === path) return {};
  const escaped = pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // 支持 :param(*) 形式（贪婪匹配，允许包含 /）；括号在 escaped 中已变为 \( \)
  const withGreedyParams = escaped.replace(
    /:([a-zA-Z0-9_]+)\\\(\*\\\)/g,
    (_m, p1) => `(?<${p1}>.*)`,
  );
  const withParams = withGreedyParams.replace(
    /:([a-zA-Z0-9_]+)/g,
    (_m, p1) => `(?<${p1}>[^/]+)`,
  );
  const withWildcard = withParams.replace(/\\\*/g, '(?<wildcard>.*)');
  const regex = new RegExp(`^${withWildcard}$`);
  const match = path.match(regex);
  if (!match) return null;
  return (match.groups || {}) as Record<string, string>;
}

/**
 * 静态路由查找。
 * - 传入 `method` 时：同一路径多项（如 GET list / POST create）按 `methods` 区分，避免永远命中列表里的第一条。
 * - 省略 `method` 时：保持旧行为，返回路径匹配的第一条（供测试与无需区分的场景）。
 */
export function findRoute(
  path: string,
  method?: string,
): { route: Route; params: Record<string, string> } | undefined {
  const m = method?.toUpperCase();
  for (const route of ROUTES) {
    const params = matchPattern(route.path, path);
    if (!params) continue;
    if (!m) {
      return { route, params };
    }
    if (!route.methods?.length) {
      return { route, params };
    }
    if (route.methods.map((x) => x.toUpperCase()).includes(m)) {
      return { route, params };
    }
  }
  return undefined;
}









































