export const ALLOWED_RPC_PATTERNS = [
  // auth
  'auth.validate',
  // users
  'users.findAll',
  'users.findOne',
  'users.create',
  'users.update',
  'users.remove',
  'users.memberships.list',
  'users.adminContext.get',
  // companies
  'companies.findAll',
  'companies.creationQuota',
  'companies.findOne',
  'companies.create',
  'companies.quickCreate',
  'companies.createDraft',
  'companies.completeWizard',
  'companies.update',
  'companies.changeStatus',
  'companies.remove',
  'companies.validateAccess',
  'companies.membership.findActive',
  'companies.ceoDecision.getConfig',
  'companies.ceoDecision.updateConfig',
  'companies.ceoLayerConfig.getConfig',
  'companies.ceoLayerConfig.updateConfig',
  'companies.ceoLayerConfig.syncSkillsToAgent',
  'companies.ceoLayerConfig.syncFromTemplate',
  'companies.ceoLayerConfig.atomicSync',
  'marketplace.skills.listAvailableVersions',
  'marketplace.skills.upgradeVersion',
  // organization
  'organization.tree',
  'organization.node.create',
  'organization.department.addFromPlatform',
  'organization.node.update',
  'organization.node.move',
  'organization.node.remove',
  'organization.node.agents',
  'organization.node.reportingChain',
  'organization.node.skills.list',
  'organization.node.skills.bind',
  'organization.node.skills.unbind',
  'organization.audit.logs',
  'organization.node.knowledgeSummary',
  // agents
  'agents.findAll',
  'agents.uiConfig',
  'agents.systemApproval',
  'agents.findOne',
  'agents.create',
  'agents.batchRecruit',
  'agents.update',
  'agents.remove',
  'agents.assignToNode',
  'agents.updateStatus',
  'agents.bindSkills',
  'agents.unbindSkills',
  'agents.effectiveSkills',
  'agents.effectiveSkillSnapshots',
  'agents.effectiveExecutionRoles',
  'agents.approve',
  'agents.auditLogs',
  'agents.memoryStats',
  'agents.management.subordinates',
  'agents.management.supervisorChain',
  'agents.refreshMarketplaceLlmSnapshot',
  'agents.hierarchy.setSupervisor',
  // skills
  'skills.findAll',
  'skills.findOne',
  'skills.validateCompanyBindings',
  'skills.create',
  'skills.update',
  'skills.remove',
  'skills.revisions.list',
  'skills.revisions.importFromArtifact',
  'skills.revisions.publish',
  'skills.revisions.review',
  'skills.revisions.revoke',
  'skills.revisions.rollback',
  // collaboration
  'collaboration.rooms.list',
  'collaboration.rooms.findMain',
  'collaboration.rooms.findDepartmentBySlug',
  'collaboration.rooms.findOne',
  'collaboration.rooms.markRead',
  'collaboration.rooms.updateCollaborationMode',
  'collaboration.orchestrationRuns.listByRoom',
  'collaboration.orchestrationRuns.workerUpsert',
  'collaboration.programs.getActive',
  'collaboration.programs.listByRoom',
  'collaboration.programs.workerMutate',
  'collaboration.programs.confirm',
  'collaboration.rooms.mergeMetadata',
  'collaboration.mainRoomDraft.state.get',
  'collaboration.mainRoomDraft.strategyGoal.patch',
  'collaboration.mainRoomDraft.distribution.patch',
  'collaboration.dispatchPlanDraft.state.get',
  'collaboration.dispatchPlanDraft.patch',
  'collaboration.threads.list',
  'collaboration.threads.create',
  'collaboration.threads.update',
  'collaboration.threads.incrementRound',
  'collaboration.messages.patchMetadata',
  'collaboration.messages.send',
  'collaboration.messages.appendAgent',
  'collaboration.messages.list',
  'collaboration.messages.search',
  'collaboration.members.remove',
  'collaboration.room.summary.request',
  'collaboration.members.list',
  'collaboration.members.add',
  'collaboration.members.addFromOrganizationNode',
  'collaboration.rooms.createDepartment',
  'collaboration.organizationNodes.search',
  'collaboration.director.reportProgress',
  // tasks / dashboard
  'tasks.findAll',
  'tasks.findOne',
  'tasks.create',
  'tasks.update',
  'tasks.remove',
  'tasks.assign',
  'tasks.delegateByDirector',
  'tasks.reviewByDirector',
  'tasks.reviewBatchByDirector',
  'tasks.director.generateProgressReport',
  'tasks.updateProgress',
  'tasks.departmentPipeline.createSequential',
  'tasks.departmentPipeline.crossDepartmentHandoff',
  'tasks.supervision.resolve',
  'tasks.tree',
  'tasks.requestBreakdown',
  'tasks.executionLog.append',
  'tasks.executionLog.appendForRun',
  'tasks.executionLogs.list',
  'tasks.executionLogs.listByRunId',
  'tasks.executionLogs.groupedByRun',
  'tasks.dependencies.list',
  'tasks.run.start',
  'tasks.run.complete',
  'tasks.run.fail',
  'tasks.runs.list',
  'tasks.runs.get',
  'tasks.runs.intervene',
  'observability.trace.listByRunId',
  'dashboard.companySummary',
  'dailyBrief.getForUser',
  'dashboard.billingSummary',
  'dashboard.boardRunSummary',
  // billing
  'billing.records.list',
  'billing.record.append',
  'billing.budgets.list',
  'billing.budget.upsert',
  'billing.settings.get',
  'billing.settings.update',
  'billing.modelRouter.resolve',
  'billing.checkAllowance',
  'billing.agentUsage.listCompanyDaily',
  'billing.agentUsage.listRange',
  'billing.costTrend.get',
  'billing.signals.refresh',
  'billing.agentLlmPricingSnapshot',
  'billing.rechargeOrders.list',
  'billing.rechargeOrders.create',
  'billing.rechargeOrders.approve',
  'billing.rechargeOrders.reject',
  // M4 approval gate
  'approval.create',
  'approval.list',
  'approval.listPending',
  'approval.findOne',
  'approval.stats',
  'approval.approve',
  'approval.reject',
  'approval.consumeExecutionToken',
  'approval.applyGatedConfig',
  // alerts / risk monitor
  'alerts.list',
  'alerts.resolve',
  // M5 supervisor
  'supervisor.review.enqueue',
  'supervisor.review.runManual',
  'supervisor.metrics.retrospective',
  'supervisor.lessons.recent',
  // memory
  'memory.entries.list',
  'memory.entries.store',
  'memory.entries.archive',
  'memory.entries.unarchive',
  'memory.search',
  'memory.search.hierarchy',
  'memory.search.routed',
  'memory.summarize',
  'memory.consolidation.request',
  'memory.session.backfill.request',
  'memory.document.ingest',
  'memory.document.ingestAsync',
  // files
  'files.list',
  'files.getUrl',
  'files.getInfo',
  'files.delete',
  // file-assets
  'fileAssets.findAll',
  'fileAssets.getStats',
  'fileAssets.findOne',
  'fileAssets.update',
  'fileAssets.remove',
  'fileAssets.getDownloadUrl',
  'fileAssets.ingest',
  'fileAssets.register',
  'fileAssets.markIngestStatus',
  'fileAssets.readText',
  'fileAssets.registerFromContent',
  // templates / marketplace
  'templates.findAll',
  'templates.findOne',
  'templates.preview',
  'templates.import',
  'marketplace.agents.findAll',
  'marketplace.agents.findOne',
  'marketplace.agents.purchase',
  'marketplace.hireRequests.create',
  'marketplace.hireRequests.list',
  'marketplace.hireRequests.findOne',
  'marketplace.hireRequests.approve',
  'marketplace.hireRequests.reject',
  // oauth
  'oauth.bind',
  'oauth.accounts',
  'oauth.findOrCreate',
  // webhooks
  'webhooks.create',
  'webhooks.findAll',
  'webhooks.findOne',
  'webhooks.update',
  'webhooks.remove',
  'webhooks.history',
] as const;

export function isAllowedRpcPattern(pattern: string | undefined): boolean {
  if (!pattern) return false;
  return (ALLOWED_RPC_PATTERNS as readonly string[]).includes(pattern);
}

