export const ALLOWED_RPC_PATTERNS = [
  // auth
  'auth.validate',
  // users
  'users.findAll',
  'users.findOne',
  'users.create',
  'users.update',
  'users.remove',
  // companies
  'companies.findAll',
  'companies.findOne',
  'companies.create',
  'companies.quickCreate',
  'companies.createDraft',
  'companies.completeWizard',
  'companies.update',
  'companies.changeStatus',
  'companies.validateAccess',
  // organization
  'organization.tree',
  'organization.node.create',
  'organization.node.update',
  'organization.node.move',
  'organization.node.remove',
  'organization.node.agents',
  'organization.node.reportingChain',
  'organization.node.skills.list',
  'organization.node.skills.bind',
  'organization.node.skills.unbind',
  'organization.audit.logs',
  'organization.node.knowledgeSummary',
  // agents
  'agents.findAll',
  'agents.findOne',
  'agents.create',
  'agents.batchRecruit',
  'agents.update',
  'agents.remove',
  'agents.assignToNode',
  'agents.updateStatus',
  'agents.bindSkills',
  'agents.unbindSkills',
  'agents.effectiveSkills',
  'agents.effectiveSkillSnapshots',
  'agents.approve',
  'agents.auditLogs',
  'agents.memoryStats',
  // skills
  'skills.findAll',
  'skills.findOne',
  'skills.create',
  'skills.update',
  'skills.remove',
  'skills.revisions.list',
  'skills.revisions.importFromArtifact',
  'skills.revisions.publish',
  'skills.revisions.review',
  'skills.revisions.revoke',
  'skills.revisions.rollback',
  // collaboration
  'collaboration.rooms.list',
  'collaboration.rooms.findMain',
  'collaboration.rooms.findOne',
  'collaboration.rooms.updateCollaborationMode',
  'collaboration.rooms.mergeMetadata',
  'collaboration.threads.list',
  'collaboration.threads.create',
  'collaboration.threads.update',
  'collaboration.threads.incrementRound',
  'collaboration.messages.patchMetadata',
  'collaboration.messages.send',
  'collaboration.messages.appendAgent',
  'collaboration.messages.list',
  'collaboration.messages.search',
  'collaboration.members.remove',
  'collaboration.room.summary.request',
  'collaboration.members.list',
  'collaboration.members.add',
  'collaboration.members.addFromOrganizationNode',
  'collaboration.rooms.createDepartment',
  'collaboration.organizationNodes.search',
  // tasks / dashboard
  'tasks.findAll',
  'tasks.findOne',
  'tasks.create',
  'tasks.update',
  'tasks.remove',
  'tasks.assign',
  'tasks.updateProgress',
  'tasks.tree',
  'tasks.requestBreakdown',
  'tasks.executionLog.append',
  'tasks.executionLogs.list',
  'tasks.executionLogs.groupedByRun',
  'tasks.dependencies.list',
  'tasks.run.start',
  'tasks.run.complete',
  'tasks.run.fail',
  'tasks.runs.list',
  'dashboard.companySummary',
  'dashboard.billingSummary',
  'dashboard.boardRunSummary',
  // billing
  'billing.records.list',
  'billing.record.append',
  'billing.budgets.list',
  'billing.budget.upsert',
  'billing.settings.get',
  'billing.settings.update',
  'billing.modelRouter.resolve',
  'billing.checkAllowance',
  'billing.signals.refresh',
  // memory
  'memory.entries.store',
  'memory.search',
  'memory.search.hierarchy',
  'memory.search.routed',
  'memory.summarize',
  'memory.consolidation.request',
  'memory.session.backfill.request',
  'memory.document.ingest',
  'memory.document.ingestAsync',
  // files
  'files.list',
  'files.getUrl',
  'files.getInfo',
  'files.delete',
  // templates / marketplace
  'templates.findAll',
  'templates.findOne',
  'templates.preview',
  'templates.import',
  'marketplace.agents.findAll',
  'marketplace.agents.findOne',
  'marketplace.agents.purchase',
  'marketplace.hireRequests.create',
  'marketplace.hireRequests.list',
  'marketplace.hireRequests.findOne',
  'marketplace.hireRequests.approve',
  'marketplace.hireRequests.reject',
  // oauth
  'oauth.bind',
  'oauth.accounts',
  'oauth.findOrCreate',
  // webhooks
  'webhooks.create',
  'webhooks.findAll',
  'webhooks.findOne',
  'webhooks.update',
  'webhooks.remove',
  'webhooks.history',
] as const;

export function isAllowedRpcPattern(pattern: string | undefined): boolean {
  if (!pattern) return false;
  return (ALLOWED_RPC_PATTERNS as readonly string[]).includes(pattern);
}

