param(
    [string]$Source = ".env.shared",
    [string]$Target = "deployment/docker",
    [string]$Service = "",
    [switch]$Help
)

if ($Help) {
    Write-Host @"
Env manager script

Usage:
  .\scripts\env-manager.ps1 [-Source <file>] [-Target <dir>] [-Service <name>]

Services:
  gateway, api, webhooks, worker, logging, docker
"@
    exit 0
}

if (-not (Test-Path $Source)) {
    Write-Error "Source file not found: $Source"
    exit 1
}

function Parse-EnvFile {
    param([string]$content)
    $variables = @{}
    $lines = $content -split "`r?`n"

    foreach ($line in $lines) {
        $trimmed = $line.Trim()
        if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) {
            continue
        }
        if ($trimmed -match '^([^#=]+?)\s*=\s*(.*)$') {
            $key = $matches[1].Trim()
            $value = $matches[2].Trim()

            # Remove inline comment for unquoted values.
            if (-not ($value.StartsWith('"') -or $value.StartsWith("'"))) {
                $commentIndex = $value.IndexOf("#")
                if ($commentIndex -ge 0) {
                    $value = $value.Substring(0, $commentIndex).Trim()
                }
            }

            # Strip matching quotes.
            if ($value -match '^"(.*)"$') {
                $value = $matches[1]
            } elseif ($value -match "^'(.*)'$") {
                $value = $matches[1]
            }

            $variables[$key] = $value
        }
    }

    return $variables
}

function Ensure-Directory {
    param([string]$filePath)
    $dir = Split-Path $filePath -Parent
    if (-not [string]::IsNullOrWhiteSpace($dir) -and -not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

function Generate-ServiceEnvFile {
    param(
        [hashtable]$variables,
        [string[]]$requiredVars,
        [string]$outputPath,
        [string]$serviceName
    )

    $localVars = @{}
    foreach ($k in $variables.Keys) {
        $localVars[$k] = $variables[$k]
    }

    $out = @()
    $out += "# $serviceName service env"
    $out += "# generated by scripts/env-manager.ps1"
    $out += "# generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $out += ""

    switch ($serviceName) {
        "gateway" {
            $out += "NODE_ENV=$($localVars['NODE_ENV'])"
            $out += "PORT=$($localVars['GATEWAY_SERVICE_PORT'])"
            $out += ""
            if ($localVars.ContainsKey('GATEWAY_DB_DATABASE')) { $localVars['DB_DATABASE'] = $localVars['GATEWAY_DB_DATABASE'] }
            if ($localVars.ContainsKey('REDIS_DB_GATEWAY')) { $localVars['REDIS_DB'] = $localVars['REDIS_DB_GATEWAY'] }
        }
        "api" {
            $out += "NODE_ENV=$($localVars['NODE_ENV'])"
            $out += "PORT=$($localVars['API_SERVICE_PORT'])"
            $out += ""
            if ($localVars.ContainsKey('API_DB_DATABASE')) { $localVars['DB_DATABASE'] = $localVars['API_DB_DATABASE'] }
            if ($localVars.ContainsKey('REDIS_DB_API')) { $localVars['REDIS_DB'] = $localVars['REDIS_DB_API'] }
        }
        "webhooks" {
            $out += "NODE_ENV=$($localVars['NODE_ENV'])"
            $out += "PORT=$($localVars['WEBHOOKS_SERVICE_PORT'])"
            if ($localVars.ContainsKey('APP_VERSION')) { $out += "APP_VERSION=$($localVars['APP_VERSION'])" }
            $out += ""
        }
        "worker" {
            $out += "NODE_ENV=$($localVars['NODE_ENV'])"
            $out += "PORT=$($localVars['WORKER_SERVICE_PORT'])"
            if ($localVars.ContainsKey('APP_VERSION')) { $out += "APP_VERSION=$($localVars['APP_VERSION'])" }
            $out += ""
        }
        "logging" {
            $out += "NODE_ENV=$($localVars['NODE_ENV'])"
            $out += "PORT=$($localVars['LOGGING_SERVICE_PORT'])"
            if ($localVars.ContainsKey('HOSTNAME')) { $out += "HOSTNAME=$($localVars['HOSTNAME'])" }
            $out += ""
        }
    }

    $added = @{}
    foreach ($var in $requiredVars) {
        if ($localVars.ContainsKey($var)) {
            $out += "$var=$($localVars[$var])"
            $added[$var] = $true
        }
    }

    Ensure-Directory -filePath $outputPath
    $out -join "`n" | Out-File -FilePath $outputPath -Encoding utf8 -NoNewline
    Write-Host "Generated: $outputPath" -ForegroundColor Green
}

function Generate-DockerEnvFile {
    param(
        [hashtable]$variables,
        [string]$outputPath
    )

    $dockerVars = @{}
    foreach ($k in $variables.Keys) {
        $dockerVars[$k] = $variables[$k]
    }

    $dockerVars['DB_HOST'] = 'postgres'
    $dockerVars['REDIS_HOST'] = 'redis'
    $dockerVars['RABBITMQ_HOST'] = 'rabbitmq'
    $dockerVars['RABBITMQ_URI'] = "amqp://$($dockerVars['RABBITMQ_USER']):$($dockerVars['RABBITMQ_PASSWORD'])@rabbitmq:$($dockerVars['RABBITMQ_PORT'])/"
    $dockerVars['RMQ_URL'] = $dockerVars['RABBITMQ_URI']
    $dockerVars['API_SERVICE_URL'] = 'http://api-service:3000'
    $dockerVars['WEBHOOKS_SERVICE_URL'] = 'http://webhooks-service:3003'
    $dockerVars['WORKER_SERVICE_URL'] = 'http://worker-service:3004'
    $dockerVars['LOGGING_SERVICE_URL'] = 'http://logging-service:3001'
    $dockerVars['LOKI_URL'] = 'http://loki:3100'
    if ($dockerVars.ContainsKey('CONSUL_HOST')) { $dockerVars['CONSUL_HOST'] = 'consul' }

    $out = @()
    $out += "# docker env"
    $out += "# generated by scripts/env-manager.ps1"
    $out += "# generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $out += ""
    foreach ($k in ($dockerVars.Keys | Sort-Object)) {
        $out += "$k=$($dockerVars[$k])"
    }

    Ensure-Directory -filePath $outputPath
    $out -join "`n" | Out-File -FilePath $outputPath -Encoding utf8 -NoNewline
    Write-Host "Generated: $outputPath" -ForegroundColor Green
}

$serviceConfigs = @{
    "gateway" = @(
        "NODE_ENV","PORT","JWT_SECRET","JWT_REFRESH_SECRET","JWT_EXPIRES_IN","JWT_REFRESH_EXPIRES_IN",
        "DB_HOST","DB_PORT","DB_USERNAME","DB_PASSWORD","DB_DATABASE","DB_SYNCHRONIZE","DB_LOGGING",
        "REDIS_HOST","REDIS_PORT","REDIS_PASSWORD","REDIS_DB",
        "API_SERVICE_URL","WEBHOOKS_SERVICE_URL","WORKER_SERVICE_URL","LOGGING_SERVICE_URL",
        "RMQ_URL","RATE_LIMIT_TTL","RATE_LIMIT_MAX_REQUESTS","RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS",
        "CIRCUIT_BREAKER_ENABLED","CIRCUIT_BREAKER_FAILURE_THRESHOLD","CIRCUIT_BREAKER_SUCCESS_THRESHOLD",
        "CIRCUIT_BREAKER_TIMEOUT","CIRCUIT_BREAKER_RESET_TIMEOUT",
        "WECHAT_APP_ID","WECHAT_APP_SECRET","WECHAT_REDIRECT_URI","WECHAT_SCOPE","FRONTEND_URL",
        "AUTHORIZATION_ENABLED","METRICS_ADAPTER","METRICS_ENABLE_DEFAULT_COLLECTORS",
        "PROMETHEUS_COLLECT_DEFAULT_METRICS","PROMETHEUS_PREFIX",
        "HTTP_TIMEOUT","CORS_ORIGIN","CORS_CREDENTIALS",
        "SWAGGER_ENABLED","SWAGGER_PATH",
        "ENCRYPTION_ADAPTER","AES_KEY","AES_ALGORITHM","AES_KEY_LENGTH",
        "CONSUL_ENABLED","CONSUL_HOST","CONSUL_PORT","CONSUL_CONFIG_PREFIX","CONSUL_SECURE","CONSUL_TOKEN","CONSUL_DATACENTER"
    )
    "api" = @(
        "NODE_ENV","PORT","JWT_SECRET","JWT_REFRESH_SECRET","JWT_EXPIRES_IN","JWT_REFRESH_EXPIRES_IN",
        "DB_HOST","DB_PORT","DB_USERNAME","DB_PASSWORD","DB_DATABASE","DB_SYNCHRONIZE","DB_LOGGING",
        "REDIS_HOST","REDIS_PORT","REDIS_PASSWORD","REDIS_DB",
        "CACHE_ADAPTER_TYPE","METRICS_ADAPTER","METRICS_ENABLED","PROMETHEUS_COLLECT_DEFAULT_METRICS","PROMETHEUS_PREFIX",
        "RMQ_URL","HTTP_TIMEOUT","CORS_ORIGIN","CORS_CREDENTIALS",
        "ENCRYPTION_ADAPTER","AES_KEY","HASHING_ADAPTER","BCRYPT_SALT_ROUNDS",
        "STORAGE_TYPE","STORAGE_LOCAL_BASE_PATH","STORAGE_LOCAL_BASE_URL",
        "STORAGE_MINIO_ENDPOINT","STORAGE_MINIO_PORT","STORAGE_MINIO_USE_SSL",
        "STORAGE_MINIO_ACCESS_KEY","STORAGE_MINIO_SECRET_KEY","STORAGE_MINIO_BUCKET_NAME",
        "SWAGGER_ENABLED","SWAGGER_PATH","TEST_AUTH_ENABLED",
        "CONSUL_ENABLED","CONSUL_HOST","CONSUL_PORT","CONSUL_CONFIG_PREFIX","CONSUL_SECURE","CONSUL_TOKEN","CONSUL_DATACENTER"
    )
    "webhooks" = @("NODE_ENV","PORT","APP_VERSION","CONSUL_ENABLED","CONSUL_HOST","CONSUL_PORT","CONSUL_CONFIG_PREFIX","CONSUL_SECURE","CONSUL_TOKEN","CONSUL_DATACENTER")
    "worker" = @("NODE_ENV","PORT","APP_VERSION","RABBITMQ_HOST","RABBITMQ_PORT","RABBITMQ_USER","RABBITMQ_PASSWORD","RABBITMQ_VHOST","RABBITMQ_URI","RABBITMQ_PREFETCH_COUNT","RABBITMQ_RECONNECT_DELAY","RABBITMQ_MAX_RETRIES","CONSUL_ENABLED","CONSUL_HOST","CONSUL_PORT","CONSUL_CONFIG_PREFIX","CONSUL_SECURE","CONSUL_TOKEN","CONSUL_DATACENTER")
    "logging" = @("NODE_ENV","PORT","HOSTNAME","LOKI_URL","ELASTICSEARCH_URL","ELASTICSEARCH_INDEX_PREFIX","LOG_DIR","CONSUL_ENABLED","CONSUL_HOST","CONSUL_PORT","CONSUL_CONFIG_PREFIX","CONSUL_SECURE","CONSUL_TOKEN","CONSUL_DATACENTER")
}

$envContent = Get-Content $Source -Raw
$envVars = Parse-EnvFile -content $envContent

if ([string]::IsNullOrWhiteSpace($Service)) {
    foreach ($serviceName in $serviceConfigs.Keys) {
        Generate-ServiceEnvFile -variables $envVars -requiredVars $serviceConfigs[$serviceName] -outputPath "apps/$serviceName/.env" -serviceName $serviceName
    }
    Generate-DockerEnvFile -variables $envVars -outputPath "$Target/.env"
    exit 0
}

if ($Service -eq "docker") {
    Generate-DockerEnvFile -variables $envVars -outputPath "$Target/.env"
    exit 0
}

if ($serviceConfigs.ContainsKey($Service)) {
    Generate-ServiceEnvFile -variables $envVars -requiredVars $serviceConfigs[$Service] -outputPath "apps/$Service/.env" -serviceName $Service
    exit 0
}

Write-Error "Unknown service: $Service"
Write-Host "Available services: $($serviceConfigs.Keys -join ', '), docker"
exit 1

