-- 仅填充职能能力三列（不修改 sort_order / display_name），对齐 SeedExtendedPlatformDepartments 的 17 个 slug。
-- 在 AddPlatformDepartmentCapabilities20260522140000 迁移之后执行。

UPDATE platform_departments SET responsibility_summary = '工程部负责产品研发、工程实现、技术可行性与代码交付。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["software_delivery","tech_feasibility"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'engineering';
UPDATE platform_departments SET responsibility_summary = '设计部负责UI/UX、视觉稿与设计系统。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["design_delivery","brand_copy"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'design';
UPDATE platform_departments SET responsibility_summary = '营销部负责品牌、获客、市场活动与 organic 增长。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["brand_copy","lead_generation","growth_metrics","marketing_content"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'marketing';
UPDATE platform_departments SET responsibility_summary = '付费媒体部负责付费投放、广告账户与投放效果优化。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["paid_acquisition","lead_generation","growth_metrics"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'paid-media';
UPDATE platform_departments SET responsibility_summary = '销售部负责商机跟进、签约与客户收入达成。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["lead_generation","growth_metrics"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'sales';
UPDATE platform_departments SET responsibility_summary = '金融财务部负责预算、核算、税务、审计与财务合规。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["finance_audit","budget"]'::jsonb, excludes_task_type_tags = '["lead_generation","social_media_ops","growth_metrics"]'::jsonb, updated_at = now() WHERE slug = 'finance';
UPDATE platform_departments SET responsibility_summary = '人力资源部负责招聘、人事流程、薪酬与组织发展。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["hr_recruiting","hr_operations"]'::jsonb, excludes_task_type_tags = '["social_media_ops","paid_acquisition"]'::jsonb, updated_at = now() WHERE slug = 'hr';
UPDATE platform_departments SET responsibility_summary = '法务部负责合同审查、合规与知识产权。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["legal_contract"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'legal';
UPDATE platform_departments SET responsibility_summary = '供应链部负责采购、库存、物流与供应商管理。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["supply_chain_ops"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'supply-chain';
UPDATE platform_departments SET responsibility_summary = '产品部负责需求定义、PRD、路线图与验收标准。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["product_discovery","project_coordination"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'product';
UPDATE platform_departments SET responsibility_summary = '项目管理部负责里程碑、排期与跨部门项目协调。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["project_coordination"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'project-management';
UPDATE platform_departments SET responsibility_summary = '测试部负责测试策略、用例与质量门禁。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["qa_testing","software_delivery"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'qa';
UPDATE platform_departments SET responsibility_summary = '支持部负责客户工单、售后与满意度。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["customer_support"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'support';
UPDATE platform_departments SET responsibility_summary = '专项部负责跨职能专项攻关与临时项目交付。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["project_coordination","strategy_planning"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'special-projects';
UPDATE platform_departments SET responsibility_summary = '空间计算部负责空间计算、XR 相关工程与产品实现。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["software_delivery","tech_feasibility","design_delivery"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'spatial-computing';
UPDATE platform_departments SET responsibility_summary = '游戏开发部负责游戏客户端、玩法实现与技术交付。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["software_delivery","tech_feasibility"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'game-development';
UPDATE platform_departments SET responsibility_summary = '战略部负责战略规划、竞争与市场进入分析。对接跨部门需求时以可验收交付物为边界。', task_type_tags = '["strategy_planning"]'::jsonb, excludes_task_type_tags = '[]'::jsonb, updated_at = now() WHERE slug = 'strategy';
